# Generated by Django 2.2.18 on 2021-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_anon_id_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollmentcelebration',
            name='first_day_of_streak',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollmentcelebration',
            name='last_day_of_streak',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollmentcelebration',
            name='last_streak_celebration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
